version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtb-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - rtb-network

  webserver:
    image: nginx:alpine
    container_name: rtb-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - rtb-network

  db:
    image: mysql:8.0
    container_name: rtb-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306"
    environment:
     MYSQL_DATABASE: rtb_db
     MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - rtb-network

  redis:
    image: redis:alpine
    container_name: rtb-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/data
    networks:
      - rtb-network

networks:
  rtb-network:
    driver: bridge